### ISSUE TITLE
请问这个自动获取token的方案有办法用python实现吗？

### ISSUE THREAD

**Issue by irebix** [MiraculousB/not-in-campus#1]

**Comment by MiraculousB** [comment]
语言不是问题，只是之前我没有找到python有能够获取https流量的库。你也可以自己写一个，就是比较费时间

**Comment by irebix** [comment]
import urllib.request
import ssl
 
ssl._create_default_https_context = ssl._create_unverified_context
response = urllib.request.urlopen('https://www.python.org')
print(response.read().decode('utf-8'))
 
这两个库能行么•́ω•̀)

**Comment by MiraculousB** [comment]
不行吧，你可以去搜一下python中间人攻击
