### ISSUE TITLE
安装通过pip安装requests时报错，网上方法都试了没有解决，换了国内的源也是这样

### ISSUE THREAD

**Issue by jarryxy** [MiraculousB/not-in-campus#2]
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7efe31f11a30>: Failed to establish a new connection: [Errno -2] Name or service not known')': /pypi/simple/pip/

**Comment by desire599** [comment]
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7efe31f11a30>: Failed to establish a new connection: [Errno -2] Name or service not known')': /pypi/simple/pip/
